import express from "express";
import jwt from "jsonwebtoken";
import { JWT_SECRET } from "@repo/backend-common/config";
import { middleware } from "./middleware";
import { CreateUserSchema, SignInSchema, CreateRoomSchema } from "@repo/common/types";
import { prismaClient } from "@repo/db/client";
import cors from "cors";
import bcrypt from "bcrypt";
const app = express();
app.use(express.json());//json middleware
app.use(cors())

app.post("/api/v1/signup", async (req, res) => {
    const parsedData = CreateUserSchema.safeParse(req.body);//can use parse 1:01 pt 2
    if (!parsedData.success) {
        res.json({
            message: "Incorrect inputs"
        })
        return;
    }
    const email = parsedData.data?.username;
    const password = parsedData.data?.password;
    const name = parsedData.data.name;

    //db call
    //creating a user
    try {
        const hashedPassword = await bcrypt.hash(password, 5);
        const user = await prismaClient.user.create({
            data: {
                email: email,
                password: hashedPassword,
                name: name
            }
        })

        res.json({
            userId: user.id,
            message: "user signed up"
        })
    } catch (e) {
        res.status(411).json({
            message: "User already exists with this username"
        })
    }
});

app.post("/api/v1/signin", async (req, res) => {

    const parsedData = SignInSchema.safeParse(req.body);
    if (!parsedData.success) {
        res.json({
            message: "Incorrect inputs"
        })
        return;
    }
    const email = parsedData.data?.username;
    const password = parsedData.data?.password;
    const user = await prismaClient.user.findFirst({
        where: {
            email: email,
        }
    })

    if (!user) {
        res.status(403).json({
            message: "Not authorized"
        })
        return;
    }

    const passwordMatch = await bcrypt.compare(password, user.password);

    if (passwordMatch) {
        const token = jwt.sign({
            userId: user?.id
        }, JWT_SECRET);

        res.json({
            token
        })
    } else {
        res.status(403).json({
            message: "Incorrect credentials"
        })
    }



});


//route to create a room & create a entry in db
app.post("/api/v1/room", middleware, async (req, res) => {
    const parsedData = CreateRoomSchema.safeParse(req.body);
    if (!parsedData.success) {
        res.json({ message: "Incorrect inputs" });
        return;
    }

    const userId = req.userId;

    if (!userId) {
        res.status(401).json({ message: "Unauthorized" });
        return;
    }

    try {
        const room = await prismaClient.room.create({
            data: {
                name: parsedData.data.name,
                admin: { connect: { id: userId } },

                // inviteCode auto-generated by Prisma default(uuid())
                // slug auto-generated by Prisma default(uuid())
            }
        });

        // Admin should automatically join the room
        await prismaClient.roomMember.create({
            data: {
                userId,
                roomId: room.id
            }
        });

        res.json({
            message: "Room created",
            roomId: room.id,
            slug: room.slug,
            inviteCode: room.inviteCode // useful to share directly
        });

    } catch (e) {
        console.log(e);
        res.status(500).json({ message: "Error creating room" });
    }
});



//will hit this endpoint to get all the chats of existing room
app.get("/api/v1/chats/:roomId", async (req, res) => {

    try {
        const roomId = Number(req.params.roomId);

        //hitting the db and getting top 1000 messages
        const messages = await prismaClient.chat.findMany({
            where: {
                roomId: roomId
            },
            orderBy: {
                id: "desc"
            },
            take: 1000
        });
        res.json({
            messages
        })
    } catch (e) {
        res.json({
            messages: []
        })
    }
})

app.delete("/api/v1/chats/:id", async (req, res) => {
    try {
        const id = Number(req.params.id);
        await prismaClient.chat.delete({
            where: { id },
        });
        res.json({ message: `deleted ${id}` });
    } catch (e) {
        res.status(500).json({ message: "Error deleting message" });
    }
});


//given a slug return a roomid. when the user comes they will come to /room/chat-room-1
app.get("/api/v1/room/:slug", async (req, res) => {
    const slug = req.params.slug;
    const room = await prismaClient.room.findFirst({
        where: {
            slug
        }
    })
    res.json({
        room
    })
})

//get all rooms endpoint
app.get("/api/v1/rooms", middleware, async (req, res) => {
    const userId = req.userId;
  
    try {
      const rooms = await prismaClient.room.findMany({
        where: {
          OR: [
            { adminId: userId },                     // rooms user created
            { members: { some: { userId } } }       // rooms user joined
          ]
        },
        orderBy: { createdAt: "desc" },
        include: {
          admin: { select: { name: true } }
        }
      });
  
      res.json({ rooms });
  
    } catch (e) {
      console.log(e);
      res.status(500).json({
        message: "Error fetching rooms"
      });
    }
  });
  


app.post("/api/v1/room/join/:inviteCode", middleware, async (req, res) => {
    const { inviteCode } = req.params;
    const userId = req.userId;

    if (!userId) {
        res.status(401).json({ message: "Unauthorized" });
        return;
    }

    try {
        const room = await prismaClient.room.findFirst({
            where: { inviteCode }
        });

        if (!room) {
            res.status(404).json({ message: "Invalid or expired invite link" });
            return;
        }

        await prismaClient.roomMember.upsert({
            where: {
                userId_roomId: {
                    userId,
                    roomId: room.id
                }
            },
            update: {},
            create: {
                userId,
                roomId: room.id
            }
        });

        res.json({
            message: "Joined room",
            roomId: room.id,
            slug: room.slug
        });
        return;

    } catch (e) {
        console.log(e);
        res.status(500).json({ message: "Error joining room" });
        return;
    }
});


app.get("/api/v1/room/:roomId/invite", middleware, async (req, res) => {
    const roomId = Number(req.params.roomId);
    const userId = req.userId;

    const room = await prismaClient.room.findFirst({
        where: {
            id: roomId,
            adminId: userId  // Only admin can get invite link
        }
    });

    if (!room) {
        res.status(403).json({ message: "Not allowed" });
        return;
    }

    res.json({
        inviteLink: `http://localhost:3000/invite/${room.inviteCode}`
    });
});



app.listen(3001);